### ISSUE TITLE
CSS rules for icons for context menu entries don't work since last update

### ISSUE THREAD

**Issue by bege10** [ancestorak/brief#242]
Via CSS rules I have added icons to the context menu entries in order to have better clarity. Although the IDs of the entries have not changed the icons don't appear any more since the last update of Brief. What may be the reason and how can I change this?

**Comment by tanriol** [comment]
Where do you put the CSS rules?

**Comment by bege10** [comment]
By now they were in a CSS file with other rules for menu icons of all kind of context menus in Firefox, loded with the JS-script userCSSLoader.uc.js https://github.com/ardiman/userChrome.js/tree/master/usercssloader

Now I tried it in the brief settings. Both ways don't work.

Here's a sample rule:
`#ctx-feed-properties, #ctx-feed-settomgs, #brief-options-menuitem, {-moz-image-region:rect(80px 176px 96px 160px)!important; list-style-image:url(file://F:/Users/bege/AppData/Roaming/Mozilla/icons/mosaic.png)!important}`

**Comment by sleek22** [comment]
I can confirm this.

When I installed Brief 2.3.0, it opened up with a wide sidebar and one of my folders fully expanded. I narrowed the sidebar and closed the folder and on opening Brief again, the same thing happened, i.e., it wasn't keeping the settings. I found out by accident that if I refreshed Brief after adjusting it, it retained its settings. Clearing the cache did not help as I thought Brief, now using xhtml, might be reading an old page.

Before the above, I went into options and tried setting the #sidebar to a smaller width with no response. I tried selectors with more specificity but it made no difference. My old settings, however, seemed to be unaffected. For example I used the following code to color the left bar on items red for easier viewing. That still works. So it could be that only some CSS settings don't work.

article.selected> .full-container> .full-container-inner {border-left: 2px solid #FF0000 !important}

I'm currently back on Brief 2.2.2

**Comment by tanriol** [comment]
@bege10 
On HTML pages `list-style-image` does not work without `display: list-item;` which, unfortunately, will break the UI quite a bit. Please try the following instead:
```css
#ctx-feed-properties::before,
#ctx-feed-settomgs::before,
#brief-options-menuitem::before {
    content: "";
    height: 16px;
    width: 16px;
    background-image: url(file://F:/Users/bege/AppData/Roaming/Mozilla/icons/mosaic.png);
    background-position: -80px -160px;
}
```

**Comment by tanriol** [comment]
@sleek22 This is a different issue that I cannot reproduce. For me Brief keeps the settings correctly. In Brief 2.3 they're stored in a preference `extensions.brief.pagePersist`.

As for the sidebar width, the page code sets it to the value loaded from preferences using inline CSS, so this CSS property is expected not to work.

**Comment by tanriol** [comment]
@sleek22 I'm closing this issue (the support question on CSS selectors). If you want to help in finding and fixing the issue with lost settings, please open a new one.

**Comment by bege10** [comment]
@tanriol 
Thank you, but unfortunately this doesn't make a change.
As said before, the rules worked until the last update of Brief. All necessary command to show list style images in the browser are part of the CSS file. The images for all other context menus in Firefox and extensions keep on working.

**Comment by tanriol** [comment]
The following code in Brief's customize window works for me
```css
#ctx-feed-properties::before,
#ctx-feed-settomgs::before,
#brief-options-menuitem::before {
    content: "" !important;
    height: 16px !important;
    width: 16px !important;
    background-position: -32px -104px !important;
    background-image: url(file:///home/username/path/to/image.png) !important;
}
```
> As said before, the rules worked until the last update of Brief.

In the last update the menus were moved from the browser chrome into the Brief tab (and from XUL to XHTML), so both the CSS that works for them and the CSS sources used have changed.

> All necessary command to show list style images in the browser are part of the CSS file. The images for all other context menus in Firefox and extensions keep on working.

Does this stylesheet apply to documents with chrome origin, but loaded inside a tab?
