### ISSUE TITLE
Adjusting font size

### ISSUE THREAD

**Issue by Freudentaumel** [ancestorak/brief#320]
How can I change the font size in the feed list? To avoid misunderstandings: By feedlist I mean the left column with the titles of the subscribed feeds.

**Comment by tanriol** [comment]
Use the CSS editor in the Brief's settings with something like
```css
tree-folder-header .title,
tree-item .title {
    font-size: large !important;
}
```
