### ISSUE TITLE
[Public request] CSS customization for dark theme.

### ISSUE THREAD

**Issue by githubtefo** [ancestorak/brief#326]
Hi! by chance, anyone has a custom CSS script for Brief to change the colors to Dark (grey background, bright fonts, etc.)?
Thank you in advance!

**Comment by tanriol** [comment]
Also, if a viable dark theme is suggested, it may become an official theme later.

**Comment by bb84000** [comment]
Hello, 

Please try this none :

[userchrome.zip](https://github.com/ancestorak/brief/files/1547464/userchrome.zip)

Paste the content in the Brief option page's customize box.

bb

**Comment by githubtefo** [comment]
Thank you @bb84000!
I modified your dark theme, please find  that version here: 
[brief-custom-style-dark_b.css.txt](https://github.com/ancestorak/brief/files/1572580/brief-custom-style-dark_b.css.txt)

**Comment by bb84000** [comment]
Hello,

I've add some items to the customization

[brief-custom-style-dark.zip](https://github.com/ancestorak/brief/files/1572771/brief-custom-style-dark.zip)

bb

**Comment by VillageCatDad** [comment]
Nice!  However, "Organize" mode is unreadable.  White text on an orange background?  Is there some way to change that?

**Comment by bb84000** [comment]
Hello,

Thank you for the Organize mode bug.

The new version correct this

[brief-custom-style-dark.zip](https://github.com/ancestorak/brief/files/1586119/brief-custom-style-dark.zip)

Merry Christmas !

bb

**Comment by VillageCatDad** [comment]
Merry Christmas, and thanks!

Although when I press organize now, the folder names are white font on white background.  The feed names look fine, it’s just the folder names (when not hovering).

**Comment by bb84000** [comment]
Hello,

New version with proper optimize customization :

[brief-custom-style-dark.zip](https://github.com/ancestorak/brief/files/1587118/brief-custom-style-dark.zip)

Please continue to find bugs or disfunction of this "theme"!
bb

**Comment by VillageCatDad** [comment]
Thank you!

In normal reading mode, I’m still having an issue with the contrast between the selected folder and the folder name’s font color.  See attached:



Maybe if the background highlight were a bit darker?  It also washes out the unread article count.

Again, appreciate your work!  Thanks again,
  S.

**Comment by bb84000** [comment]
Hello, 
You can easily change colors. The feedname colors are here:
/* Feed name color */
  --feedname: #f2f2f2 ;
  --sel-feedname: #454545;
  --sel-feedname-bkgr: #d2d2d2;
  --over-feedname-bkgr: #c2c2c2;

Coulor scheme is #rrggbb, 00 is no color,  ff is full colour.  
<#000000 : black
#ffffff : `white
#ff0000 : red
etc.>

bb

**Comment by eberhardweber** [comment]
[ShadowFox](https://github.com/overdodactyl/ShadowFox) developer overdodactyl has recently written [a preliminary Brief stylesheet](https://github.com/overdodactyl/ShadowFox/blob/master/webextensions/brief.css) to match his Firefox dark theme.

If anyone wants to help the dev with further modifications, you can open [a new issue at the bug tracker](https://github.com/overdodactyl/ShadowFox/issues) with amendments and corrections. 

@tanriol may be interested in considering it for an official theme as well given that it matches the rest of Firefox's dark theme.

**Comment by clessley** [comment]
I made one also here: [https://github.com/clessley/Dark-Theme-for-Brief-RSS-Reader](https://github.com/clessley/Dark-Theme-for-Brief-RSS-Reader)

**Comment by lostthing** [comment]
I made this custom dark theme CSS, all icons replaced by emojis. Any enhancement is welcome, happy hacking :)

![ss](https://user-images.githubusercontent.com/95527107/144706706-f5ed3a65-09c9-4188-9fb6-271d837e2b99.jpg)

[brief_rss.css.txt](https://github.com/brief-rss/brief/files/7653768/brief_rss.css.txt)

**Comment by bb84000** [comment]
Well !
I will test it on windows...
bb

**Comment by githubtefo** [comment]
Looks very nice! I'm using it, thank you!

BTW, every time I open Brief there is a withe flash before the dark theme appears. Does anyone know how to avoid this behavior?

**Comment by bb84000** [comment]
> BTW, every time I open Brief there is a withe flash before the dark theme appears. Does anyone know how to avoid this behavior?

It is the Brief database loading  time. As database grows with time, this time can become very long, specially when the hard disk is busy. There is a way to reset Brief.

**Save the dark theme css file** and **export your feeds to opml file**. Remember the **Brief ID in the browser address** bar.
Then go to the "storage/default/" folder in the firefox profile and delete the **folders related to the Brief ID**. Same operation in the storage/permanent/" folder .

Then copy the theme css file in the Options box.

Brief will reload the feeds and their contents.

bb

**Comment by lostthing** [comment]
> Looks very nice! I'm using it, thank you!
> 
> BTW, every time I open Brief there is a withe flash before the dark theme appears. Does anyone know how to avoid this behavior?

Seems we cant avoid it from CSS custom, the page source:
![ss](https://user-images.githubusercontent.com/95527107/144736283-8a14c9b4-165e-4577-9b1b-6bc7b38d5eef.png)

#custom-css was separated from other stylesheets and loaded last. 

Maybe Link preload can, which requires a source code patch https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload

**Comment by tanriol** [comment]
The problem here is that the custom CSS is loaded from script, and requires an async operation - likely a cross-process IPC, which can be slow. When/if I have time to get back to Brief, I'll look into speeding this up, unless someone does that before then.

**Comment by atomGit** [comment]
here's another dark theme, albeit a  **very quick and dirty** hack - i may improve it over time if i continue to use brief

<details>
<summary>click</summary>

```css
html {
    background: #000 !important;
}

/* SIDEBAR */
#sidebar-splitter,
#tag-list-splitter {
    border-left: 3px solid #626262 !important;
    border-right: unset !important;
}
#sidebar {
    background-color: #2b2b2b !important;
}
.sidebar-button {
    color: #ff6800 !important;
}
#sidebar-top {
    border-bottom: 3px solid #626262 !important;
}
#view-list {
    background-color: #353535 !important;
    padding-bottom: 10px !important;
}
#view-list > tree-item > .title {
    color: unset !important;
}
tree-box {
    border-bottom: 3px solid #626262 !important;
}
tree-folder {
    margin: 5px 0 5px 8px !important;
}
tree-folder-header {
    padding: 0 !important;
    border: none !important;
}
tree-folder-header > .toggle-collapsed {
    opacity: 0.4;
}
tree-folder-header > .toggle-collapsed {
    opacity: 1;
}
tree-folder:not(.selected) > tree-folder-header:hover {
    background-color: #455b76 !important;
    border-color: #2b2b2b !important;
}
tree-item {
    padding: unset !important;
}
tree-item:hover:not(.selected),
tree-item > .title,
tree-folder-header > .title,
tree-folder-footer > .title {
    color: unset !important;
}
tree-item.selected,
tree-folder.selected > tree-folder-header {
    background-color: #455b76 !important;
    border: none !important;
}
tree-item > .icon,
tree-item > .system-icon {
    border: 1px solid #a2a2a2 !important;
}

/* ARTICLES PANE HEADER */
#feed-view-header {
    background: #2b2b2b !important;
}
#view-title-label {
color: #ff6800 !important;
}
.controls {
    background: #000;
}
#searchbar {
    color: unset !important;
}

/* ARTICLES PANE */
body {
    background: #2b2b2b;
}
#feed-content .full-container {
    flex: 0 1 90% !important;
    max-width: 1200px !important;
}
.headline-container {
    flex: auto !important;
    overflow: visible !important;
    flex: 0 1 90% !important;
    max-width: 1200px !important;
    white-space: wrap !important;
    color: #a4a4a4 !important;
}
.headline-container:hover > .headline-header {
    background-color: #4a4a4a !important;
}
.headline-feed-name {
    height: unset !important;
}
.day-header {
    background: #bd1d1d !important;
    padding: 10px 0 10px 20px !important;
    font-weight: bold;
}
.headline-title {
    height: unset;
    white-space: wrap;
    overflow: visible;
    color: #deddda;
}
.full-container-inner {
    border: none !important;
    background: none !important;
}
.title-link {
    color: #bfbfbf;
    overflow: visible;
}
.content a {
    color: #ff6800;
}
.content {
    color: #deddda !important;
    text-align: unset !important;
}
```

</details>
